API_LIST.yml
CTD_api/CTD_openapi.yml
GT_cmaq_exposures_api/cmaq_exposures_openapi.yml

tests.py wasn't passing before these changes, so I fixed a couple of minor YAML formatting things and added a couple of general tags in order to get this YAML file to pass

Fixed YAML validation + test failures, register CTD api

---

GT_cmaq_exposures_api/cmaq_exposures_openapi.yml

can someone else check and merge please?

fixes to make CI tests pass

---

GTEx_api/smartapi-3.0.yaml

openapi definition spec for the GTEx API

openapi spec for the GTEx API

---

robokop/openapi.yml

per https://github.com/NCATS-Tangerine/translator-api-registry/#specific-notes-for-adding-a-reasoner-api

additional info

---

mydisease.info/smartapi.yaml

align with https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml

standardize capitalization

---

mydisease.info/smartapi.yaml

ctd disease-bp and bp-disease replaced with disease-pathway and pathway-disease,
example queries to run added for each operation,
inverse operations added

fix mydisease operations

---

mychem.info/openapi_full.yml

Also add a pmid response-mapping. 
Notes are on whether inputs/outputs can have more ID namespaces, on whether predicate is currently in biolink model or not.

Change size limits, predicates. Add notes

---

mychem.info/openapi_full.yml

adjusted comments to show that there are alternative IDs (we aren't going to expose them right now, so we don't do redundant queries).
Linked to https://github.com/biolink/biolink-model/pull/680 for metabolic_processing_affected_by, is_contraindication_for

Made predicates biolink or biolink-PR

---

ols/smartapi.yaml

@kevinxin90 Do ASAP if you approve

update biolink predicate, source format

---

dgidb/smartapi.yml

Not sure if this file is actually used. openapi file is what is actually used by BTE

Fix true typo

---

uberon/smartapi.yaml

location_of and develops_from operations won't work until these fixes for typos go thru

Fix typos, location_of query, biolink predicates

---

drug_response_kp/smartapi.yaml

one predicate is still in [biolink PR](https://github.com/biolink/biolink-model/blob/10b659736b419d1a8721c4150e029202ac9b9270/biolink-model.yaml#L2318)

fix ncbigene error

---

biolink/openapi.yml

This API uses NCBIGene as its prefix, so when that was added to the parameter string, I changed its case to this.

Add source, fix querying issue with ncbigene

---

biothings_explorer/smartapi.yaml

@newgene Review this, make sure the changes work the way we want, then merge. 
Part of doing this: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/171

Update BTE to latest v, TRAPI 1.1.0 endpoints

---

LINCS/smartapi.yml
dgidb/openapi.yml
dgidb/smartapi.yml
drug_response_kp/smartapi.yaml
idisk/smartapi.yaml
mychem.info/openapi_full.yml
mydisease.info/smartapi.yaml
myvariant.info/openapi_full.yml
opentarget/smartapi.yaml
semmed/semmed_anatomy.yaml
semmed/semmed_biological_process.yaml
semmed/semmed_chemical.yaml
semmed/semmed_disease.yaml
semmed/semmed_gene.yaml
semmed/semmed_phenotype.yaml
text_mining/cooccurrence.yaml
text_mining/smartapi.yaml

fix: ChemicalSubstance -> SmallMolecule, add x-translator.biolink-version to more apis

merge for biolink v2.1 updates

---

text_mining/smartapi.yaml

covers the newly updated API + supports batch queries (multiple IDs in 1 query, with POST)

update targeted association api

---

molecular_data_provider/MolePro-TRAPI-1.2.yaml

MolePro: Add x-translator.infores and x-maturity

MolePro: Add x-translator.infores and x-maturity

---

biothings_explorer/smartapi.yaml

will bring this up-to-date, matching https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml

fix: BTE check-job-status endpoint fixes

---

drug_response_kp/smartapi.yaml

not complete yet:
see comments in the yaml and
https://github.com/biothings/pending.api/issues/56 and https://github.com/TranslatorSRI/NodeNormalization/issues/113

drug response kp api update

---

biothings_explorer/smartapi.yaml

keep the BTE smartapi yaml here in-sync with https://github.com/biothings/BioThings_Explorer_TRAPI/blob/dryrun/docs/smartapi.yaml.
Then merge after the change from that PR is deployed

bte: add dryrun parameter, update biolink version

---

bioplanet/bioplanet-pathway-gene.yaml

I tested with a pathway to gene and gene to pathway query w/ BTE.
<details>
<summary>Example Query</summary>
```json
{
"message": {
"query_graph": {
"nodes": {
"n0": {
"ids": ["BIOPLANET:bioplanet_906"],
"categories":["biolink:Pathway"]
},
"n1": {
"ids":["NCBIGene:10053"],
"categories":["biolink:Gene"]
}
},
"edges": {
"e01": {
"subject": "n1",
"object": "n0"
}
}
}
}
}
```
</details>
<details>
<summary>Example Response</summary>
```json
{
"workflow": [
{
"id": "lookup"
}
],
"message": {
"query_graph": {
"nodes": {
"n0": {
"ids": [
"BIOPLANET:bioplanet_906"
],
"categories": [
"biolink:Pathway"
]
},
"n1": {
"ids": [
"NCBIGene:10053"
],
"categories": [
"biolink:Gene"
]
}
},
"edges": {
"e01": {
"subject": "n1",
"object": "n0"
}
}
},
"knowledge_graph": {
"nodes": {
"BIOPLANET:bioplanet_906": { …
```

Create Bioplanet Pathway Gene smartapi yaml

---

bindingdb/smartapi.yaml

This adds an OpenAPI YAML for the Biothings BindingDB API
<details>
<summary>Example BTE Query</summary>
input
```json
{
"message": {
"query_graph": {
"nodes": {
"n0": {
"ids": ["UniProtKB:P35372"],
"categories": ["biolink:Protein"]
},
"n1": {
"ids": ["INCHIKEY:IZBUEYQBUXFDCK-UHFFFAOYSA-N"],
"categories": ["biolink:SmallMolecule"]
}
},
"edges": {
"e01": {
"subject": "n0",
"object": "n1"
}
}
}
}
}
```
output
```json
{
"workflow":[
{
"id":"lookup"
}
],
"message":{
"query_graph":{
"nodes":{
"n0":{
"ids":[
"UniProtKB:P35372"
],
"categories":[
"biolink:Protein",
"biolink:Gene"
]
},
"n1":{
"ids":[
"INCHIKEY:IZBUEYQBUXFDCK-UHFFFAOYSA-N"
],
"categories":[
"biolink:SmallMolecule"
]
}
},
"edges":{
"e01":{
"subject":"n0",
"object":"n1"
}
}
},
"knowledge_graph":{
"nodes":{ …
```

BindingDB API YAML

---

biothings_explorer/service-provider-trapi.yaml
biothings_explorer/service-provider-trapi_temp13.yaml
biothings_explorer/smartapi.yaml
biothings_explorer/smartapi_temp13.yaml

Related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/490 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/472 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/450

bte/service provider: make small updates to trapi1.2 and add trapi1.3 yamls

---

drug_response_kp/smartapi.yaml

not ready to merge. Wait until fixes and re-deployment of BioThings API are done, then check/edit this yaml...

multiomics biggim drug-response: update server url and operations

---

text_mining/smartapi.yaml

This is to catch the ITRB version up to the changes that do not require qualified predicates.

Adding operations under /query and removing low-count operations

---

text_mining/smartapi.yaml

Fixing a mismatch between input and request body for some operations
Removing operations for combinations that don't exist in the data anymore

Bugfix and removing unused operations

---

drug_response_kp/smartapi.yaml

related to this commit https://github.com/gloriachin/translator-api-registry/commit/8becba7b90e75bb00f15ccf21e4ab0636533116b

adding trapi 1.4 sources field

---

drug_response_kp/smartapi.yaml

revised CL

---

mychem.info/openapi_full.yml

WAIT until UI team is using infores updates that have `infores:fda-orphan-drug-db` https://github.com/biolink/biolink-model/pull/1429
To address https://github.com/biothings/biothings_explorer/issues/709

mychem: edit fda-orphan-data operations

---

pfocr/smartapi.yaml

Related to https://github.com/biothings/biothings_explorer/issues/882
Don't merge until [pending BioThings update](https://github.com/biothings/pending.api/issues/241) and BTE override has been deployed to all instances 
Then can start process of removing BTE's override to this branch's yaml.

pfocr: add chebi/doid namespaces

---

mydisease.info/smartapi.yaml

also can retrieve publications in reverse direction (but operations are non-batch)

mydisease disgenet: add score-thresholds and special-rev handling
